import { PrismaClient, InvoiceType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting vendor seed...');

  const vendors = [
    {
      name: 'Avery Dennison Paxar (China) Ltd',
      name_aliases: ['Paxar (China) Limited', 'PAXAR CHINA', 'Avery Dennison Paxar China'],
      expected_template: InvoiceType.INV,
      supplier_location: 'China',
      swift_code: 'SCBLHKHHXXX',
      account_usd: '447-0-092575-1',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Avery Dennison Hong Kong B.V.',
      name_aliases: ['Avery Dennison HK', 'ADV HK', 'Avery Dennison Hong Kong BV'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Hong Kong',
      swift_code: 'SCBLHKHHXXX',
      account_usd: '447-0-092572-7',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Avery Dennison (PT. Paxar Indonesia)',
      name_aliases: ['PT Paxar Indonesia', 'PT. Paxar Indonesia'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Indonesia',
      swift_code: 'CITIIDJX',
      account_usd: '0-106656-509',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Avery Dennison RIS Vietnam Co., Ltd',
      name_aliases: ['Avery Dennison RIS Vietnam', 'Avery Dennison Vietnam'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Vietnam',
      swift_code: 'CITIVNVXHCM',
      account_usd: '0302103 003',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'UPW Limited',
      name_aliases: ['UPW Ltd', 'UPW HK'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Hong Kong',
      swift_code: 'BKCHHKHH',
      account_usd: '012-878-92198787',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Amass International Limited',
      name_aliases: ['Amass International Ltd', 'AMASS INTL', 'Goodbox'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Hong Kong',
      swift_code: 'ICBCHKHH',
      account_usd: '965-11-021998',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Punarbhavaa Sustainable Products Pvt Ltd',
      name_aliases: ['Punarbhavaa', 'PSP', 'PSPPL'],
      expected_template: InvoiceType.PI,
      supplier_location: 'India',
      swift_code: 'KVBLINBBIND',
      account_usd: '1234149000000400',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Charming Printing Ltd',
      name_aliases: ['Charming', 'CTRIM'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Hong Kong',
      swift_code: 'HSBCHKHHHKH',
      account_usd: '808-190896-838',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Ducksan Enterprise Co., Ltd',
      name_aliases: ['Ducksan', 'Duck San Enterprise'],
      expected_template: InvoiceType.INV,
      supplier_location: 'South Korea',
      swift_code: 'IBKOKRSEXXX',
      account_usd: '218-021292-56-00017',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Trimco Group (Hong Kong) Co. Ltd',
      name_aliases: ['Trimco HK', 'Trimco'],
      expected_template: InvoiceType.PI,
      supplier_location: 'Hong Kong',
      swift_code: 'CTCBHKHH',
      account_usd: '904101089259',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Master Air International Inc',
      name_aliases: ['Master Air', 'Master Air Inc'],
      expected_template: InvoiceType.INV,
      supplier_location: 'USA',
      bank_name: 'Chase Bank',
      aba_routing_number: '21000021',
      account_usd: '946588266',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Far Dar Express Worldwide (HK) Ltd',
      name_aliases: ['Far Dar', 'FDE Express', 'FAR DAR'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Hong Kong',
      swift_code: 'BKCHHKHH',
      account_usd: '012-878-0-800740-6',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Seaman Paper Asia Co. Ltd',
      name_aliases: ['Seaman Paper Asia'],
      expected_template: InvoiceType.PI,
      supplier_location: 'Hong Kong',
      swift_code: 'HSBCHKHHHKH',
      account_usd: '808-026348-838',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'R-PAC Vietnam Limited',
      name_aliases: ['R-PAC VN', 'r-pac Vietnam', 'r-pac International'],
      expected_template: InvoiceType.CI,
      supplier_location: 'Vietnam',
      swift_code: 'HSBCVNVX',
      account_usd: '001-819812-101',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Rudholm & Haak (HK) Ltd',
      name_aliases: ['Rudholm HK', 'Rudholm'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Hong Kong',
      swift_code: 'CITIHKHXXX',
      account_usd: '006-391-62470558',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Checkpoint Systems Limited',
      name_aliases: ['Checkpoint Systems', 'Checkpoint'],
      expected_template: InvoiceType.SI,
      supplier_location: 'Hong Kong',
      swift_code: 'HSBCHKHHHKH',
      account_usd: '741-291777-201',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'PT SML Indonesia Private',
      name_aliases: ['PT SML Indonesia', 'SML Indonesia'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Indonesia',
      swift_code: 'HSBCIDJA',
      account_usd: '050-063767-007',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Brand ID LLC',
      name_aliases: ['Brand ID', 'BID'],
      expected_template: InvoiceType.INV,
      supplier_location: 'USA',
      swift_code: 'FCBTUS33',
      aba_routing_number: '053100300',
      account_usd: '001064456562',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Bo Hing Label Industries Co. Ltd',
      name_aliases: ['Bo Hing', 'BO HING LABEL'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Hong Kong',
      swift_code: 'SCBLHKHHXXX',
      account_usd: '329-0-029493-4',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'C&T Label Company Limited',
      name_aliases: ['C&T Label', 'C & T Label', 'CT Label'],
      expected_template: InvoiceType.PI,
      supplier_location: 'Hong Kong',
      swift_code: 'SCBLHKHHXXX',
      account_usd: '003-446-1-029005-6',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Dong Guan City Ocan Weaving Co., Ltd',
      name_aliases: ['Dong Guan Ocan', 'Ocan Weaving', '东莞市欧肯织造'],
      expected_template: InvoiceType.PI,
      supplier_location: 'China',
      swift_code: 'DHBKHKHH',
      account_usd: '79969429145',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Longqing Garment Accessories Co., Ltd',
      name_aliases: ['Longqing', 'Dragon Times', 'DRAGON TIMES'],
      expected_template: InvoiceType.PI,
      supplier_location: 'China',
      swift_code: 'ICBKCNBJDGN',
      account_usd: '2010012209144500463',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'G&F Trading (Hong Kong) Limited',
      name_aliases: ['G&F Trading', 'G & F Trading', 'G&F HK'],
      expected_template: InvoiceType.PI,
      supplier_location: 'Hong Kong',
      swift_code: 'UBHKHKHH',
      account_usd: '072-716-056-000379',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Lee Bou International Binh Duong Co. Ltd',
      name_aliases: ['Lee Bou', 'LEE BOU VN'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Vietnam',
      swift_code: 'VBAAVNVX',
      account_usd: '5500 201 034 545',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Perfect China Supplies Ltd',
      name_aliases: ['Perfect China', 'PERFECT CHINA'],
      expected_template: InvoiceType.INV,
      supplier_location: 'China',
      swift_code: 'BEASHKHH',
      account_usd: '015-178-40-002484',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Nilorn East Asia Limited',
      name_aliases: ['Nilorn EA', 'Nilorn East Asia', 'Nilorn HK'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Hong Kong',
      swift_code: 'HSBCHKHHHKH',
      account_usd: '500-775408-201',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Nilorn Shanghai Trading Company Ltd',
      name_aliases: ['Nilorn Shanghai', 'Nilorn CN'],
      expected_template: InvoiceType.INV,
      supplier_location: 'China',
      swift_code: 'ESSECNSH',
      account_usd: '18700112',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Jointak Labels Company Limited',
      name_aliases: ['Jointak', 'JOINTAK LABELS'],
      expected_template: InvoiceType.PI,
      supplier_location: 'Hong Kong',
      swift_code: 'HSBCHKHHHKH',
      account_usd: '004-741-406268-838',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Avery Dennison RIS Vietnam Co., Ltd',
      name_aliases: ['Avery Dennison RIS Vietnam', 'Avery Dennison Vietnam'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Vietnam',
      swift_code: 'CITIVNVXHCM',
      account_usd: '0302103 003',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Weavabel',
      name_aliases: ['Weavabel UK', 'Weavabel Ltd'],
      expected_template: InvoiceType.INV,
      supplier_location: 'UK',
      swift_code: 'HBUKGB4B',
      iban: 'GB93HBUK40127677221792',
      sort_code: '40-12-76',
      account_usd: '77221792',
      vat_number: '303 4973 69',
      eori_number: 'GB303497369000',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Zhejiang Weixing Imp.&Exp Co., Ltd',
      name_aliases: ['Zhejiang Weixing', 'WEIXING'],
      expected_template: InvoiceType.PI,
      supplier_location: 'China',
      swift_code: 'ICBKCNBJZJP',
      intermediary_bank_swift: 'BOFAUS3N',
      intermediary_bank_name: 'Bank of America N.A.',
      account_usd: '1207021109814022149',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Manohar Filaments Pvt Ltd',
      name_aliases: ['Manohar Filaments', 'MFPL'],
      expected_template: InvoiceType.PI,
      supplier_location: 'India',
      swift_code: 'KKBKINBB',
      intermediary_bank_swift: 'IRVTUS3N',
      intermediary_bank_name: 'Bank of New York',
      account_usd: '4027 1101 3275',
      gstin_number: '06AAACM1116E1Z7',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'PT Victoria Label',
      name_aliases: ['Victoria Label', 'PT Victoria'],
      expected_template: InvoiceType.SI,
      supplier_location: 'Indonesia',
      bank_name: 'Not on document — obtain separately',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'S.F. Express (Hong Kong) Limited',
      name_aliases: ['SF Express', 'SF Express HK', '顺丰速运'],
      expected_template: InvoiceType.STATEMENT,
      supplier_location: 'Hong Kong',
      swift_code: 'CITIHKHX',
      account_usd: '006-391-156250996',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Beijing Shunte Science & Technology Corporation',
      name_aliases: ['Beijing Shunte', 'Shunte', 'SHUNTE'],
      expected_template: InvoiceType.INV,
      supplier_location: 'China',
      swift_code: 'BKNBCN2N',
      account_usd: '77092025000002932',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Kabuhayan Namin Incorporated',
      name_aliases: ['Kabuhayan Namin', 'Kabuhayan', 'Superdry PH'],
      expected_template: InvoiceType.SI,
      supplier_location: 'Philippines',
      swift_code: 'BNORPHMM',
      account_usd: '1053-7004-4059',
      bir_tin: '214-289-809-00001',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Tentac Co., Ltd',
      name_aliases: ['Tentac', 'TENTAC'],
      expected_template: InvoiceType.INV,
      supplier_location: 'Vietnam',
      bank_name: 'Not on document — obtain separately',
      has_multiple_accounts: false,
      currency: 'USD',
    },
    {
      name: 'Vela Vietnam Packaging Limited Company',
      name_aliases: ['Vela Vietnam', 'Vela VN', 'VELA'],
      expected_template: InvoiceType.PI,
      supplier_location: 'Vietnam',
      swift_code: 'UOVBVNVX',
      intermediary_bank_swift: 'CHASUS33',
      intermediary_bank_name: 'JP Morgan Chase',
      account_usd: '1049238849',
      has_multiple_accounts: false,
      currency: 'USD',
    },
  ];

  for (const vendor of vendors) {
    await prisma.vendor.upsert({
      where: { name: vendor.name },
      update: {},
      create: vendor,
    });
    console.log(`Seeded vendor: ${vendor.name}`);
  }

  console.log('Vendor seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('Error seeding vendors:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
