import { Response, NextFunction } from 'express';
import { AuthRequest } from '../middleware/auth';
import { generateApiKey, hashApiKey } from '../middleware/apiKeyAuth';
import prisma from '../config/database';
import { AppError } from '../middleware/errorHandler';
import { logger } from '../utils/logger';

/**
 * POST /api/api-keys/generate
 * Generate a new API key (IT_ADMIN / SUPERADMIN only)
 */
export const generateApiKeyController = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
) => {
  try {
    const { name, expiresInDays } = req.body;

    if (!name) {
      throw new AppError('API key name is required', 400);
    }

    const { rawKey, keyHash, keyPrefix } = generateApiKey();

    const expiresAt = expiresInDays
      ? new Date(Date.now() + expiresInDays * 24 * 60 * 60 * 1000)
      : null;

    await prisma.$executeRaw`
      INSERT INTO "AP_Invoice"."APInvoice_ApiKey" (id, key_hash, key_prefix, name, created_by, created_at, expires_at)
      VALUES (gen_random_uuid(), ${keyHash}, ${keyPrefix}, ${name}, ${req.user!.id}, NOW(), ${expiresAt})
    `;

    logger.info(`API key '${name}' generated by ${req.user!.id}`);

    res.status(201).json({
      success: true,
      apiKey: rawKey,
      keyPrefix,
      name,
      expiresAt,
      message: 'Store this key securely. It will not be shown again.',
    });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/api-keys
 * List all API keys (without revealing the actual key)
 */
export const listApiKeysController = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
) => {
  try {
    const keys = await prisma.$queryRaw`
      SELECT id, key_prefix, name, created_by, created_at, revoked_at, last_used_at, expires_at
      FROM "AP_Invoice"."APInvoice_ApiKey"
      ORDER BY created_at DESC
    `;

    res.json({ success: true, keys: Array.isArray(keys) ? keys : [] });
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/api-keys/:id/revoke
 * Revoke an API key
 */
export const revokeApiKeyController = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
) => {
  try {
    const { id } = req.params;

    await prisma.$executeRaw`
      UPDATE "AP_Invoice"."APInvoice_ApiKey"
      SET revoked_at = NOW()
      WHERE id = ${id} AND revoked_at IS NULL
    `;

    logger.info(`API key ${id} revoked by ${req.user!.id}`);

    res.json({ success: true, message: 'API key revoked' });
  } catch (error) {
    next(error);
  }
};
