import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, GitCompare, ScanSearch, ShoppingCart } from 'lucide-react';
import api from '../lib/api';

const fmt = (v: any) => v == null || v === '' ? '—' : String(v);
export default function PurchasingWorkbench() {
  const [tab, setTab] = useState<'lines'|'extraction'|'duplicates'>('lines');
  const [invoices, setInvoices] = useState<any[]>([]); const [pairs, setPairs] = useState<any[]>([]); const [message, setMessage] = useState('');
  const load = async () => { const [q,d] = await Promise.all([api.get('/api/workbench/queue'), api.get('/api/workbench/duplicates')]); setInvoices(q.data); setPairs(d.data); };
  useEffect(() => { load().catch(() => setMessage('Unable to load workbench.')); }, []);
  const editLine = async (line: any, field: string) => { const value = prompt(`Correct ${field}`, fmt(line[field]) === '—' ? '' : fmt(line[field])); if (value == null) return; await api.patch(`/api/workbench/lines/${line.id}`, { [field]: ['quantity','selling_quantity','unit_price','line_amount'].includes(field) ? Number(value) : value }); setMessage('Correction saved with audit history.'); await load(); };
  const editField = async (invoice: any, field: string) => { const value = prompt(`Correct ${field}`, fmt(invoice[field]) === '—' ? '' : fmt(invoice[field])); if (value == null) return; const corrected = ['total_amount','qty_shipped'].includes(field) ? Number(value) : value; await api.patch(`/api/invoices/${invoice.id}`, { [field]: corrected }); await api.post(`/api/invoices/${invoice.id}/correct-extraction`, { vendor_name: invoice.vendor?.name, original_fields: { [field]: invoice[field] }, corrected_fields: { [field]: corrected }, note: 'Field-confidence workbench correction' }); setMessage(`${field.replace(/_/g,' ')} corrected and added to extraction learning history.`); await load(); };
  const resolve = async (p: any, resolution: string) => { await api.post(`/api/workbench/duplicates/${p.invoice.id}/resolve`, { resolution, related_invoice_id: p.match.id, note: `Resolved in side-by-side workbench as ${resolution}` }); setMessage('Duplicate decision saved.'); await load(); };
  return <div className="min-h-screen p-6" style={{background:'var(--bg-primary)',color:'var(--text-primary)'}}><div className="max-w-7xl mx-auto space-y-5">
    <div className="flex items-center gap-3"><Link to="/" className="p-2 rounded-lg" style={{background:'var(--bg-card)'}}><ArrowLeft className="h-5 w-5"/></Link><div><h1 className="text-2xl font-bold">Purchasing & Extraction Workbench</h1><p className="text-sm" style={{color:'var(--text-muted)'}}>Validate lines, correct OCR fields, track MPO consumption, and resolve document relationships.</p></div></div>
    <div className="flex gap-2">{([['lines','Line Validation',ShoppingCart],['extraction','Extraction Review',ScanSearch],['duplicates','Duplicate Resolution',GitCompare]] as any[]).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className="px-4 py-2 rounded-xl flex gap-2 items-center" style={{background:tab===id?'var(--accent-purple)':'var(--bg-card)',color:tab===id?'white':'var(--text-primary)'}}><Icon className="h-4 w-4"/>{label}</button>)}</div>
    {message&&<div className="p-3 rounded-xl" style={{background:'var(--bg-card)',border:'1px solid var(--border-color)'}}>{message}</div>}
    {tab==='lines'&&<div className="space-y-4">{invoices.filter(i=>i.invoice_lines.length).map(i=><div key={i.id} className="rounded-xl overflow-auto" style={{background:'var(--bg-card)',border:'1px solid var(--border-color)'}}><div className="p-4 font-semibold">{i.invoice_number} · {i.vendor?.name} · {i.mpo_number||'No MPO'}</div><table className="w-full text-sm"><thead><tr>{['Line','Material','MPO / Order','Qty','Selling Qty','Ordered','Previously/Total Invoiced','Remaining','Unit Price','Amount','Match'].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{i.invoice_lines.map((l:any)=><tr key={l.id} style={{borderTop:'1px solid var(--border-color)'}}><td className="p-3">{l.line_number}</td><td className="p-3 cursor-pointer" onClick={()=>editLine(l,'material_code')}>{fmt(l.material_code)}<br/><small>{fmt(l.material_name)}</small></td><td className="p-3">{fmt(l.mpo_base_number)}-{fmt(l.mpo_order_sequence)}</td><td className="p-3 cursor-pointer" onClick={()=>editLine(l,'quantity')}>{fmt(l.quantity)}</td><td className="p-3 cursor-pointer" onClick={()=>editLine(l,'selling_quantity')}>{fmt(l.selling_quantity)}</td><td className="p-3">{fmt(l.ordered_quantity)}</td><td className="p-3">{fmt(l.invoiced_quantity)}</td><td className="p-3">{fmt(l.remaining_quantity)}</td><td className="p-3 cursor-pointer" onClick={()=>editLine(l,'unit_price')}>{fmt(l.unit_price)}</td><td className="p-3">{fmt(l.line_amount)}</td><td className="p-3">{fmt(l.match_status)}</td></tr>)}</tbody></table></div>)}</div>}
    {tab==='extraction'&&<div className="grid md:grid-cols-2 gap-4">{invoices.map(i=><div key={i.id} className="p-4 rounded-xl" style={{background:'var(--bg-card)',border:'1px solid var(--border-color)'}}><div className="font-semibold mb-3">{i.invoice_number} · {i.vendor?.name}</div>{['invoice_number','invoice_date','total_amount','currency','mpo_number','material_code','qty_shipped'].map(f=><button type="button" onClick={()=>editField(i,f)} key={f} className="flex justify-between p-2 w-full text-left rounded hover:opacity-80"><span>{f.replace(/_/g,' ')}</span><span>{fmt(i[f])} <small style={{color:'var(--text-muted)'}}>({fmt(i.field_confidence?.[f]?.confidence||i.field_confidence?.[f])}%)</small></span></button>)}<Link className="inline-block mt-3 text-sm" to={`/repository?invoice=${i.id}`}>Open invoice and correction history</Link></div>)}</div>}
    {tab==='duplicates'&&<div className="space-y-4">{pairs.length===0?<div>No unresolved duplicate candidates.</div>:pairs.map((p:any)=><div key={p.invoice.id} className="p-5 rounded-xl" style={{background:'var(--bg-card)',border:'1px solid var(--border-color)'}}><div className="grid md:grid-cols-2 gap-6"><Doc title="Flagged document" i={p.invoice}/><Doc title="Possible match" i={p.match}/></div><div className="flex flex-wrap gap-2 mt-4">{['KEEP_BOTH','MARK_DUPLICATE','PROFORMA_TO_FINAL','REVISION_OF'].map(r=><button key={r} onClick={()=>resolve(p,r)} className="px-3 py-2 rounded-lg" style={{background:'var(--bg-elevated)'}}>{r.replace(/_/g,' ')}</button>)}</div></div>)}</div>}
  </div></div>;
}
function Doc({title,i}:{title:string,i:any}) { return <div><h3 className="font-bold mb-2">{title}</h3>{[['Invoice',i.invoice_number],['Type',i.invoice_type],['Vendor',i.vendor?.name],['Amount',`${i.currency} ${i.total_amount}`],['MPO',i.mpo_number],['Material',i.material_code],['Revision',i.revision]].map(([a,b])=><div className="flex justify-between p-2" key={a}><span>{a}</span><strong>{fmt(b)}</strong></div>)}</div>}
