import { Router } from 'express';
import { authenticate, authorize } from '../middleware/auth';
import { UserRole } from '@ap-invoice/shared';
import * as c from '../controllers/workbench';
const r = Router() as Router;
r.use(authenticate);
const purchasing = authorize(UserRole.PURCHASING_COORDINATOR, UserRole.PURCHASING_MANAGER, UserRole.IT_ADMIN);
const learningManager = authorize(UserRole.PURCHASING_MANAGER, UserRole.ACCOUNTING_SUPERVISOR, UserRole.IT_ADMIN);
r.get('/queue', purchasing, c.queue);
r.patch('/lines/:lineId', purchasing, c.updateLine);
r.post('/invoices/:id/relationship', purchasing, c.relate);
r.get('/duplicates', purchasing, c.duplicates);
r.post('/duplicates/:id/resolve', purchasing, c.resolveDuplicate);
r.get('/learning-rules', learningManager, c.learningRules);
r.post('/learning-rules/:id/approve', learningManager, c.approveLearningRule);
r.post('/learning-rules/:id/disable', learningManager, c.disableLearningRule);
export default r;
