// TODO: TEMPORARY MOCK DATA — replace with real backend data
// once Supabase backend is connected. This is for demo purposes only.

import { InvoiceStatus, InvoiceType, InvoiceCategory, ExceptionReason, SignatoryRole } from '@ap-invoice/shared';

export type BrandTier = 'TOP_10' | 'OTHER';

export interface MockInvoice {
  id: string;
  invoice_number: string;
  vendor_id: string;
  vendor_name: string;
  total_amount: number;
  currency: string;
  invoice_date: string;
  invoice_received_date: string;
  payment_terms: string;
  invoice_type: InvoiceType;
  category: InvoiceCategory;
  brand?: string;
  brand_code?: string;
  brand_tier?: BrandTier;
  season?: string;
  order_type?: string;
  po_number?: string;
  mpo_number?: string;
  status: InvoiceStatus;
  current_stage?: string;
  bank_name?: string;
  account_number?: string;
  swift_code?: string;
  signatures: MockSignature[];
  exceptions: MockException[];
  stage_timestamps: MockStageTimestamp[];
  audit_logs: MockAuditLog[];
  qb_invoice_id?: string;
  qb_posted_at?: string;
  paid_at?: string;
  payment_batch_id?: string;
  follow_up_tasks?: MockFollowUpTask[];
  due_date?: string;
  updated_at?: string;
  created_at?: string;
  uploaded_by?: string;
  vendor?: { name: string };
  incoterm?: string;
  bill_to_entity?: string;
  priority_flag?: boolean;
  is_urgent?: boolean;
  ocr_confidence_score?: number;
  approval_tier?: number;
  po_validation?: {
    po_found: boolean;
    comparison?: {
      vendor_match: boolean;
      amount_match: boolean;
    };
  };
}

export interface MockSignature {
  id: string;
  signatory_role: SignatoryRole;
  signatory_name: string;
  signed_at?: string;
  signature_type: 'DIGITAL' | 'MANUAL';
}

export interface MockException {
  id: string;
  invoice_id: string;
  reason: ExceptionReason;
  description: string;
  detail?: string;
  status: 'OPEN' | 'RESOLVED' | 'WAIVED';
  resolution_notes?: string;
  resolved_at?: string;
  resolved_by?: string;
  created_at: string;
}

export interface MockStageTimestamp {
  id: string;
  stage: string;
  entered_at: string;
  exited_at?: string;
  sla_hours: number;
  is_breached: boolean;
}

export interface MockAuditLog {
  id: string;
  invoice_id: string;
  action: string;
  performed_by: string;
  note: string;
  created_at: string;
}

export interface MockVendor {
  id: string;
  name: string;
  name_aliases: string[];
  supplier_location: string;
  expected_template: string;
  bank_name?: string;
  account_number?: string;
  swift_code?: string;
  iban?: string;
  has_multiple_accounts: boolean;
  bank_verified_at?: string;
  brand_code?: string;
  brand_name?: string;
  brand_tier?: BrandTier;
}

export interface MockPaymentBatch {
  id: string;
  batch_name: string;
  status: 'DRAFT' | 'PENDING_CFO' | 'APPROVED' | 'PROCESSED';
  total_amount: number;
  currency: string;
  due_date: string;
  invoice_count: number;
  invoices: string[];
  created_at: string;
  submitted_at?: string;
  approved_at?: string;
  approved_by?: string;
  processed_at?: string;
  confirmation_pdf?: string;
}

export interface MockFollowUpTask {
  id: string;
  invoice_id: string;
  task_type: string;
  assigned_to: string;
  due_date: string;
  status: 'PENDING' | 'COMPLETED';
  reminder_count: number;
  last_reminded_at?: string;
  completed_at?: string;
  notes?: string;
  created_at: string;
}

// Mock Vendors (15 vendors)
export const MOCK_VENDORS: MockVendor[] = [
  {
    id: 'v1',
    name: 'Avery Dennison Paxar (China) Ltd',
    name_aliases: ['Avery Dennison China', 'AD Paxar China'],
    supplier_location: 'China',
    expected_template: 'STANDARD',
    bank_name: 'Bank of China',
    account_number: '1234567890',
    swift_code: 'BKCHCNBJ',
    has_multiple_accounts: false,
    brand_code: 'COL',
    brand_name: 'Columbia Sportswear',
    brand_tier: 'TOP_10',
  },
  {
    id: 'v2',
    name: 'Avery Dennison Hong Kong B.V.',
    name_aliases: ['Avery Dennison HK', 'AD HK BV'],
    supplier_location: 'Hong Kong',
    expected_template: 'STANDARD',
    bank_name: 'HSBC Hong Kong',
    account_number: '0987654321',
    swift_code: 'HSBCHKHH',
    has_multiple_accounts: false,
    brand_code: 'TNF',
    brand_name: 'The North Face',
    brand_tier: 'TOP_10',
  },
  {
    id: 'v3',
    name: 'UPW Limited',
    name_aliases: ['UPW'],
    supplier_location: 'Hong Kong',
    expected_template: 'STANDARD',
    bank_name: 'Standard Chartered HK',
    account_number: '1122334455',
    swift_code: 'SCBLHKHH',
    has_multiple_accounts: false,
  },
  {
    id: 'v4',
    name: 'Amass International Limited',
    name_aliases: ['Amass Intl'],
    supplier_location: 'Hong Kong',
    expected_template: 'STANDARD',
    bank_name: 'Hang Seng Bank',
    account_number: '5566778899',
    swift_code: 'HASEHKHH',
    has_multiple_accounts: false,
    brand_code: 'PRN',
    brand_name: 'Prana',
    brand_tier: 'OTHER',
  },
  {
    id: 'v5',
    name: 'Punarbhavaa Sustainable Products',
    name_aliases: ['Punarbhavaa'],
    supplier_location: 'India',
    expected_template: 'STANDARD',
    bank_name: 'ICICI Bank',
    account_number: '9988776655',
    swift_code: 'ICICINBB',
    has_multiple_accounts: false,
    brand_code: 'PRN',
    brand_name: 'Prana',
    brand_tier: 'OTHER',
  },
  {
    id: 'v6',
    name: 'Dong Guan City Ocan Weaving',
    name_aliases: ['Ocan Weaving', 'Dong Guan Ocan'],
    supplier_location: 'China',
    expected_template: 'STANDARD',
    bank_name: 'China Construction Bank',
    account_number: '4455667788',
    swift_code: 'CCBCCNBJ',
    has_multiple_accounts: false,
    brand_code: 'UA',
    brand_name: 'Under Armour',
    brand_tier: 'TOP_10',
  },
  {
    id: 'v7',
    name: 'R-PAC Vietnam Limited',
    name_aliases: ['R-PAC Vietnam', 'RPAC'],
    supplier_location: 'Vietnam',
    expected_template: 'STANDARD',
    bank_name: 'Vietcombank',
    account_number: '3344556677',
    swift_code: 'BFTVVNVX',
    has_multiple_accounts: false,
    brand_code: 'FJL',
    brand_name: 'Fjallraven',
    brand_tier: 'TOP_10',
  },
  {
    id: 'v8',
    name: 'Seaman Paper Asia',
    name_aliases: ['Seaman Paper'],
    supplier_location: 'Thailand',
    expected_template: 'STANDARD',
    bank_name: 'Bangkok Bank',
    account_number: '7788990011',
    swift_code: 'BKKBTHBK',
    has_multiple_accounts: false,
  },
  {
    id: 'v9',
    name: 'Zhejiang Weixing',
    name_aliases: ['Weixing', 'Zhejiang Weixing Industrial'],
    supplier_location: 'China',
    expected_template: 'STANDARD',
    bank_name: 'Industrial and Commercial Bank of China',
    account_number: '2233445566',
    swift_code: 'ICBKCNBJ',
    has_multiple_accounts: false,
  },
  {
    id: 'v10',
    name: 'Vela Vietnam Packaging',
    name_aliases: ['Vela Vietnam', 'Vela Packaging'],
    supplier_location: 'Vietnam',
    expected_template: 'STANDARD',
    bank_name: 'Vietinbank',
    account_number: '6677889900',
    swift_code: 'VNBVVNVX',
    has_multiple_accounts: false,
  },
  {
    id: 'v11',
    name: 'Brand ID LLC',
    name_aliases: ['Brand ID'],
    supplier_location: 'USA',
    expected_template: 'STANDARD',
    bank_name: 'Bank of America',
    account_number: '8900123456',
    swift_code: 'BOFAUS3N',
    has_multiple_accounts: false,
    brand_code: 'TNF',
    brand_name: 'The North Face',
    brand_tier: 'TOP_10',
  },
  {
    id: 'v12',
    name: 'S.F. Express (Hong Kong) Limited',
    name_aliases: ['SF Express', 'SF Express HK'],
    supplier_location: 'Hong Kong',
    expected_template: 'STATEMENT',
    bank_name: 'Bank of East Asia',
    account_number: '0012345678',
    swift_code: 'BEASHKHH',
    has_multiple_accounts: false,
  },
  {
    id: 'v13',
    name: 'Jointak Labels Company Limited',
    name_aliases: ['Jointak Labels', 'Jointak'],
    supplier_location: 'Hong Kong',
    expected_template: 'STANDARD',
    bank_name: 'HSBC Hong Kong',
    account_number: '0022334455',
    swift_code: 'HSBCHKHH',
    has_multiple_accounts: true, // Flag for CFO approval
  },
  {
    id: 'v14',
    name: 'PT Victoria Label',
    name_aliases: ['Victoria Label', 'PT Victoria'],
    supplier_location: 'Indonesia',
    expected_template: 'STANDARD',
    bank_name: undefined, // Missing bank info for demo
    account_number: undefined,
    swift_code: undefined,
    has_multiple_accounts: false,
  },
  {
    id: 'v15',
    name: 'Tentac Co. Ltd',
    name_aliases: ['Tentac'],
    supplier_location: 'Thailand',
    expected_template: 'STANDARD',
    bank_name: undefined, // Missing bank info for demo
    account_number: undefined,
    swift_code: undefined,
    has_multiple_accounts: false,
  },
  {
    id: 'v16',
    name: 'Global Trim Sourcing Ltd',
    name_aliases: ['Global Trim', 'Global Trim Sourcing'],
    supplier_location: 'Hong Kong',
    expected_template: 'STANDARD',
    bank_name: 'Citibank Hong Kong',
    account_number: '0044556677',
    swift_code: 'CITIHKHX',
    has_multiple_accounts: false,
    brand_code: 'TNF',
    brand_name: 'The North Face',
    brand_tier: 'TOP_10',
  },
];

// Helper function to create timestamps
const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);
const hoursAgo = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);

// Mock Invoices (20+ invoices covering all statuses and stages)
export const MOCK_INVOICES: MockInvoice[] = [
  // PENDING_VALIDATION (3 invoices)
  {
    id: 'inv1',
    invoice_number: 'HK29637599',
    vendor_id: 'v1',
    vendor_name: 'Avery Dennison Paxar (China) Ltd',
    total_amount: 1956.17,
    currency: 'USD',
    invoice_date: daysAgo(1).toISOString(),
    invoice_received_date: daysAgo(1).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Columbia Sportswear',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-COL-F26-001',
    mpo_number: 'MPO-COL-F26-001',
    status: InvoiceStatus.VALIDATION_PENDING,
    bank_name: 'Bank of China',
    account_number: '1234567890',
    swift_code: 'BKCHCNBJ',
    signatures: [],
    exceptions: [],
    stage_timestamps: [],
    audit_logs: [
      {
        id: 'al1',
        invoice_id: 'inv1',
        action: 'INVOICE_RECEIVED',
        performed_by: 'system',
        note: 'Invoice received via email intake',
        created_at: daysAgo(1).toISOString(),
      },
    ],
  },
  {
    id: 'inv2',
    invoice_number: 'DC13675',
    vendor_id: 'v3',
    vendor_name: 'UPW Limited',
    total_amount: 174.87,
    currency: 'USD',
    invoice_date: daysAgo(2).toISOString(),
    invoice_received_date: daysAgo(2).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.SAMPLE_CHARGES,
    status: InvoiceStatus.VALIDATION_PENDING,
    bank_name: 'Standard Chartered HK',
    account_number: '1122334455',
    swift_code: 'SCBLHKHH',
    signatures: [],
    exceptions: [],
    stage_timestamps: [],
    audit_logs: [
      {
        id: 'al2',
        invoice_id: 'inv2',
        action: 'INVOICE_RECEIVED',
        performed_by: 'system',
        note: 'Invoice received via email intake',
        created_at: daysAgo(2).toISOString(),
      },
    ],
  },
  {
    id: 'inv3',
    invoice_number: '20260401001',
    vendor_id: 'v6',
    vendor_name: 'Dong Guan City Ocan Weaving',
    total_amount: 2947.60,
    currency: 'USD',
    invoice_date: daysAgo(3).toISOString(),
    invoice_received_date: daysAgo(3).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Under Armour',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-UA-F26-001',
    mpo_number: 'MPO-UA-F26-001',
    status: InvoiceStatus.VALIDATION_PENDING,
    bank_name: 'China Construction Bank',
    account_number: '4455667788',
    swift_code: 'CCBCCNBJ',
    signatures: [],
    exceptions: [],
    stage_timestamps: [],
    audit_logs: [
      {
        id: 'al3',
        invoice_id: 'inv3',
        action: 'INVOICE_RECEIVED',
        performed_by: 'system',
        note: 'Invoice received via email intake',
        created_at: daysAgo(3).toISOString(),
      },
    ],
  },
  // EXCEPTION (2 invoices)
  {
    id: 'inv4',
    invoice_number: 'PCI-26018341',
    vendor_id: 'v1',
    vendor_name: 'Avery Dennison PT Paxar Indonesia',
    total_amount: 8.62,
    currency: 'USD',
    invoice_date: daysAgo(5).toISOString(),
    invoice_received_date: daysAgo(5).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    status: InvoiceStatus.EXCEPTION_FLAGGED,
    bank_name: 'Bank of China',
    account_number: '1234567890',
    swift_code: 'BKCHCNBJ',
    signatures: [],
    exceptions: [
      {
        id: 'ex1',
        invoice_id: 'inv4',
        reason: ExceptionReason.MISSING_SIGNATURE,
        description: 'Invoice missing vendor signature',
        status: 'OPEN',
        created_at: daysAgo(5).toISOString(),
      },
    ],
    stage_timestamps: [],
    audit_logs: [
      {
        id: 'al4',
        invoice_id: 'inv4',
        action: 'INVOICE_RECEIVED',
        performed_by: 'system',
        note: 'Invoice received via email intake',
        created_at: daysAgo(5).toISOString(),
      },
      {
        id: 'al5',
        invoice_id: 'inv4',
        action: 'EXCEPTION_FLAGGED',
        performed_by: 'system',
        note: 'Missing signature detected during validation',
        created_at: daysAgo(5).toISOString(),
      },
    ],
  },
  {
    id: 'inv5',
    invoice_number: 'PI151642',
    vendor_id: 'v8',
    vendor_name: 'Seaman Paper Asia',
    total_amount: 387.63,
    currency: 'USD',
    invoice_date: daysAgo(8).toISOString(),
    invoice_received_date: daysAgo(8).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.PROFORMA,
    category: InvoiceCategory.TRIMS,
    status: InvoiceStatus.EXCEPTION_FLAGGED,
    bank_name: 'Bangkok Bank',
    account_number: '7788990011',
    swift_code: 'BKKBTHBK',
    signatures: [],
    exceptions: [
      {
        id: 'ex2',
        invoice_id: 'inv5',
        reason: ExceptionReason.LATE_SUBMISSION,
        description: 'Invoice submitted 8 days after due date',
        status: 'OPEN',
        created_at: daysAgo(8).toISOString(),
      },
    ],
    stage_timestamps: [],
    audit_logs: [
      {
        id: 'al6',
        invoice_id: 'inv5',
        action: 'INVOICE_RECEIVED',
        performed_by: 'system',
        note: 'Invoice received via email intake',
        created_at: daysAgo(8).toISOString(),
      },
      {
        id: 'al7',
        invoice_id: 'inv5',
        action: 'EXCEPTION_FLAGGED',
        performed_by: 'system',
        note: 'Late submission detected',
        created_at: daysAgo(8).toISOString(),
      },
    ],
  },
  // PENDING_APPROVAL at PURCHASING_COORDINATOR stage (4 invoices)
  {
    id: 'inv6',
    invoice_number: 'INV-2026-0456',
    vendor_id: 'v2',
    vendor_name: 'Avery Dennison Hong Kong B.V.',
    total_amount: 1850.00,
    currency: 'USD',
    invoice_date: daysAgo(4).toISOString(),
    invoice_received_date: daysAgo(4).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'The North Face',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-TNF-F26-002',
    status: InvoiceStatus.PENDING_COORDINATOR,
    current_stage: 'PURCHASING_COORDINATOR',
    bank_name: 'HSBC Hong Kong',
    account_number: '0987654321',
    swift_code: 'HSBCHKHH',
    signatures: [],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st1',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: hoursAgo(24).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al8',
        invoice_id: 'inv6',
        action: 'VALIDATION_PASSED',
        performed_by: 'Sarah Jane Cariquitan',
        note: 'OCR validation completed successfully',
        created_at: hoursAgo(24).toISOString(),
      },
    ],
  },
  {
    id: 'inv7',
    invoice_number: 'INV-2026-0457',
    vendor_id: 'v4',
    vendor_name: 'Amass International Limited',
    total_amount: 2450.00,
    currency: 'USD',
    invoice_date: daysAgo(5).toISOString(),
    invoice_received_date: daysAgo(5).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Prana',
    brand_tier: 'OTHER',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-PRN-F26-003',
    status: InvoiceStatus.PENDING_COORDINATOR,
    current_stage: 'PURCHASING_COORDINATOR',
    bank_name: 'Hang Seng Bank',
    account_number: '5566778899',
    swift_code: 'HASEHKHH',
    signatures: [],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st2',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: hoursAgo(48).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al9',
        invoice_id: 'inv7',
        action: 'VALIDATION_PASSED',
        performed_by: 'Mariane Eusebio',
        note: 'OCR validation completed successfully',
        created_at: hoursAgo(48).toISOString(),
      },
    ],
  },
  {
    id: 'inv8',
    invoice_number: 'INV-2026-0458',
    vendor_id: 'v7',
    vendor_name: 'R-PAC Vietnam Limited',
    total_amount: 1950.00,
    currency: 'USD',
    invoice_date: daysAgo(6).toISOString(),
    invoice_received_date: daysAgo(6).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Fjallraven',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-FJL-F26-004',
    status: InvoiceStatus.PENDING_COORDINATOR,
    current_stage: 'PURCHASING_COORDINATOR',
    bank_name: 'Vietcombank',
    account_number: '3344556677',
    swift_code: 'BFTVVNVX',
    signatures: [],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st3',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: hoursAgo(72).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al10',
        invoice_id: 'inv8',
        action: 'VALIDATION_PASSED',
        performed_by: 'Sarah Jane Cariquitan',
        note: 'OCR validation completed successfully',
        created_at: hoursAgo(72).toISOString(),
      },
    ],
  },
  {
    id: 'inv9',
    invoice_number: 'INV-2026-0459',
    vendor_id: 'v5',
    vendor_name: 'Punarbhavaa Sustainable Products',
    total_amount: 3200.00,
    currency: 'USD',
    invoice_date: daysAgo(7).toISOString(),
    invoice_received_date: daysAgo(7).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Prana',
    brand_tier: 'OTHER',
    season: 'S26',
    order_type: 'BULK',
    po_number: 'PO-PRN-S26-001',
    status: InvoiceStatus.PENDING_COORDINATOR,
    current_stage: 'PURCHASING_COORDINATOR',
    bank_name: 'ICICI Bank',
    account_number: '9988776655',
    swift_code: 'ICICINBB',
    signatures: [],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st4',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: hoursAgo(96).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al11',
        invoice_id: 'inv9',
        action: 'VALIDATION_PASSED',
        performed_by: 'Mariane Eusebio',
        note: 'OCR validation completed successfully',
        created_at: hoursAgo(96).toISOString(),
      },
    ],
  },
  // PENDING_APPROVAL at PURCHASING_MANAGER stage (3 invoices)
  {
    id: 'inv10',
    invoice_number: 'F20260106',
    vendor_id: 'v4',
    vendor_name: 'Amass International Limited',
    total_amount: 422.25,
    currency: 'USD',
    invoice_date: daysAgo(10).toISOString(),
    invoice_received_date: daysAgo(10).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Prana',
    brand_tier: 'OTHER',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-PRN-F26-005',
    status: InvoiceStatus.PENDING_MANAGER,
    current_stage: 'PURCHASING_MANAGER',
    bank_name: 'Hang Seng Bank',
    account_number: '5566778899',
    swift_code: 'HASEHKHH',
    signatures: [
      {
        id: 'sig1',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(9).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st5',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(9).toISOString(),
        exited_at: daysAgo(8).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st6',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(8).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al12',
        invoice_id: 'inv10',
        action: 'APPROVED_BY_COORDINATOR',
        performed_by: 'Sarah Jane Cariquitan',
        note: 'Coordinator approval completed',
        created_at: daysAgo(8).toISOString(),
      },
    ],
  },
  {
    id: 'inv11',
    invoice_number: 'INV-2026-0460',
    vendor_id: 'v1',
    vendor_name: 'Avery Dennison Paxar (China) Ltd',
    total_amount: 4500.00,
    currency: 'USD',
    invoice_date: daysAgo(12).toISOString(),
    invoice_received_date: daysAgo(12).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Columbia Sportswear',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-COL-F26-006',
    status: InvoiceStatus.PENDING_MANAGER,
    current_stage: 'PURCHASING_MANAGER',
    bank_name: 'Bank of China',
    account_number: '1234567890',
    swift_code: 'BKCHCNBJ',
    signatures: [
      {
        id: 'sig2',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Mariane Eusebio',
        signed_at: daysAgo(11).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st7',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(11).toISOString(),
        exited_at: daysAgo(10).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st8',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(10).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al13',
        invoice_id: 'inv11',
        action: 'APPROVED_BY_COORDINATOR',
        performed_by: 'Mariane Eusebio',
        note: 'Coordinator approval completed',
        created_at: daysAgo(10).toISOString(),
      },
    ],
  },
  {
    id: 'inv12',
    invoice_number: 'INV-2026-0461',
    vendor_id: 'v6',
    vendor_name: 'Dong Guan City Ocan Weaving',
    total_amount: 6800.00,
    currency: 'USD',
    invoice_date: daysAgo(14).toISOString(),
    invoice_received_date: daysAgo(14).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Under Armour',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-UA-F26-007',
    status: InvoiceStatus.PENDING_MANAGER,
    current_stage: 'PURCHASING_MANAGER',
    bank_name: 'China Construction Bank',
    account_number: '4455667788',
    swift_code: 'CCBCCNBJ',
    signatures: [
      {
        id: 'sig3',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(13).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st9',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(13).toISOString(),
        exited_at: daysAgo(12).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st10',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(12).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al14',
        invoice_id: 'inv12',
        action: 'APPROVED_BY_COORDINATOR',
        performed_by: 'Sarah Jane Cariquitan',
        note: 'Coordinator approval completed',
        created_at: daysAgo(12).toISOString(),
      },
    ],
  },
  // PENDING_APPROVAL at PLANNING_MANAGER stage (2 invoices)
  {
    id: 'inv13',
    invoice_number: 'SIN870037',
    vendor_id: 'v11',
    vendor_name: 'Brand ID LLC',
    total_amount: 6200.00,
    currency: 'USD',
    invoice_date: daysAgo(16).toISOString(),
    invoice_received_date: daysAgo(16).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'The North Face',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-TNF-F26-008',
    status: InvoiceStatus.PENDING_MLO_PLANNING_MANAGER,
    current_stage: 'PLANNING_MANAGER',
    bank_name: 'Bank of America',
    account_number: '8900123456',
    swift_code: 'BOFAUS3N',
    signatures: [
      {
        id: 'sig4',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Mariane Eusebio',
        signed_at: daysAgo(15).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig5',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Maricar Tanaleon',
        signed_at: daysAgo(14).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st11',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(15).toISOString(),
        exited_at: daysAgo(14).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st12',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(14).toISOString(),
        exited_at: daysAgo(13).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st13',
        stage: 'PLANNING_MANAGER',
        entered_at: daysAgo(13).toISOString(),
        sla_hours: 96,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al15',
        invoice_id: 'inv13',
        action: 'APPROVED_BY_COORDINATOR',
        performed_by: 'Mariane Eusebio',
        note: 'Coordinator approval completed',
        created_at: daysAgo(14).toISOString(),
      },
      {
        id: 'al16',
        invoice_id: 'inv13',
        action: 'APPROVED_BY_MANAGER',
        performed_by: 'Maricar Tanaleon',
        note: 'Manager approval completed',
        created_at: daysAgo(13).toISOString(),
      },
    ],
  },
  {
    id: 'inv14',
    invoice_number: 'PSP-PI-0004633',
    vendor_id: 'v5',
    vendor_name: 'Punarbhavaa Sustainable Products',
    total_amount: 5800.00,
    currency: 'USD',
    invoice_date: daysAgo(18).toISOString(),
    invoice_received_date: daysAgo(18).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.PROFORMA,
    category: InvoiceCategory.TRIMS,
    brand: 'Prana',
    brand_tier: 'OTHER',
    season: 'S26',
    order_type: 'BULK',
    po_number: 'PO-PRN-S26-002',
    status: InvoiceStatus.PENDING_MLO_PLANNING_MANAGER,
    current_stage: 'PLANNING_MANAGER',
    bank_name: 'ICICI Bank',
    account_number: '9988776655',
    swift_code: 'ICICINBB',
    signatures: [
      {
        id: 'sig6',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(17).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig7',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Mary Ann Del Monte',
        signed_at: daysAgo(16).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st14',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(17).toISOString(),
        exited_at: daysAgo(16).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st15',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(16).toISOString(),
        exited_at: daysAgo(15).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st16',
        stage: 'PLANNING_MANAGER',
        entered_at: daysAgo(15).toISOString(),
        sla_hours: 96,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al17',
        invoice_id: 'inv14',
        action: 'APPROVED_BY_COORDINATOR',
        performed_by: 'Sarah Jane Cariquitan',
        note: 'Coordinator approval completed',
        created_at: daysAgo(16).toISOString(),
      },
      {
        id: 'al18',
        invoice_id: 'inv14',
        action: 'APPROVED_BY_MANAGER',
        performed_by: 'Mary Ann Del Monte',
        note: 'Manager approval completed',
        created_at: daysAgo(15).toISOString(),
      },
    ],
  },
  // PENDING_APPROVAL at LINDSEY stage (2 invoices)
  {
    id: 'inv15',
    invoice_number: 'PI163949',
    vendor_id: 'v10',
    vendor_name: 'Vela Vietnam Packaging',
    total_amount: 7300.20,
    currency: 'USD',
    invoice_date: daysAgo(20).toISOString(),
    invoice_received_date: daysAgo(20).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.PROFORMA,
    category: InvoiceCategory.TRIMS,
    brand: 'Vuori',
    brand_tier: 'OTHER',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-VUO-F26-001',
    status: InvoiceStatus.PENDING_SR_MANAGER,
    current_stage: 'LINDSEY',
    bank_name: 'Vietinbank',
    account_number: '6677889900',
    swift_code: 'VNBVVNVX',
    signatures: [
      {
        id: 'sig8',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Mariane Eusebio',
        signed_at: daysAgo(19).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig9',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Maricar Tanaleon',
        signed_at: daysAgo(18).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig10',
        signatory_role: SignatoryRole.MLO_PLANNING_MANAGER,
        signatory_name: 'Glecie Yumena',
        signed_at: daysAgo(17).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st17',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(19).toISOString(),
        exited_at: daysAgo(18).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st18',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(18).toISOString(),
        exited_at: daysAgo(17).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st19',
        stage: 'PLANNING_MANAGER',
        entered_at: daysAgo(17).toISOString(),
        exited_at: daysAgo(16).toISOString(),
        sla_hours: 96,
        is_breached: false,
      },
      {
        id: 'st20',
        stage: 'LINDSEY',
        entered_at: daysAgo(16).toISOString(),
        sla_hours: 72,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al19',
        invoice_id: 'inv15',
        action: 'APPROVED_BY_COORDINATOR',
        performed_by: 'Mariane Eusebio',
        note: 'Coordinator approval completed',
        created_at: daysAgo(18).toISOString(),
      },
      {
        id: 'al20',
        invoice_id: 'inv15',
        action: 'APPROVED_BY_MANAGER',
        performed_by: 'Maricar Tanaleon',
        note: 'Manager approval completed',
        created_at: daysAgo(17).toISOString(),
      },
      {
        id: 'al21',
        invoice_id: 'inv15',
        action: 'APPROVED_BY_PLANNING_MANAGER',
        performed_by: 'Glecie Yumena',
        note: 'Planning Manager approval completed',
        created_at: daysAgo(16).toISOString(),
      },
    ],
  },
  {
    id: 'inv16',
    invoice_number: 'INV-2026-0462',
    vendor_id: 'v2',
    vendor_name: 'Avery Dennison Hong Kong B.V.',
    total_amount: 8500.00,
    currency: 'USD',
    invoice_date: daysAgo(22).toISOString(),
    invoice_received_date: daysAgo(22).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'The North Face',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-TNF-F26-009',
    status: InvoiceStatus.PENDING_SR_MANAGER,
    current_stage: 'LINDSEY',
    bank_name: 'HSBC Hong Kong',
    account_number: '0987654321',
    swift_code: 'HSBCHKHH',
    signatures: [
      {
        id: 'sig11',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(21).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig12',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Mary Ann Del Monte',
        signed_at: daysAgo(20).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig13',
        signatory_role: SignatoryRole.MLO_PLANNING_MANAGER,
        signatory_name: 'Edwin Garcia',
        signed_at: daysAgo(19).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st21',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(21).toISOString(),
        exited_at: daysAgo(20).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st22',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(20).toISOString(),
        exited_at: daysAgo(19).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st23',
        stage: 'PLANNING_MANAGER',
        entered_at: daysAgo(19).toISOString(),
        exited_at: daysAgo(18).toISOString(),
        sla_hours: 96,
        is_breached: false,
      },
      {
        id: 'st24',
        stage: 'LINDSEY',
        entered_at: daysAgo(18).toISOString(),
        sla_hours: 72,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al22',
        invoice_id: 'inv16',
        action: 'APPROVED_BY_COORDINATOR',
        performed_by: 'Sarah Jane Cariquitan',
        note: 'Coordinator approval completed',
        created_at: daysAgo(20).toISOString(),
      },
      {
        id: 'al23',
        invoice_id: 'inv16',
        action: 'APPROVED_BY_MANAGER',
        performed_by: 'Mary Ann Del Monte',
        note: 'Manager approval completed',
        created_at: daysAgo(19).toISOString(),
      },
      {
        id: 'al24',
        invoice_id: 'inv16',
        action: 'APPROVED_BY_PLANNING_MANAGER',
        performed_by: 'Edwin Garcia',
        note: 'Planning Manager approval completed',
        created_at: daysAgo(18).toISOString(),
      },
    ],
  },
  // PENDING_APPROVAL at POLLY stage (1 invoice - Tier 3)
  {
    id: 'inv17',
    invoice_number: 'BULK-PO-2026-9001',
    vendor_id: 'v16',
    vendor_name: 'Global Trim Sourcing Ltd',
    total_amount: 145000.00,
    currency: 'USD',
    invoice_date: daysAgo(25).toISOString(),
    invoice_received_date: daysAgo(25).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'The North Face',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-TNF-F26-010',
    status: InvoiceStatus.PENDING_POLLY,
    current_stage: 'POLLY',
    bank_name: 'Citibank Hong Kong',
    account_number: '0044556677',
    swift_code: 'CITIHKHX',
    signatures: [
      {
        id: 'sig14',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(24).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig15',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Maricar Tanaleon',
        signed_at: daysAgo(23).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig16',
        signatory_role: SignatoryRole.MLO_PLANNING_MANAGER,
        signatory_name: 'Edwin Garcia',
        signed_at: daysAgo(22).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig17',
        signatory_role: SignatoryRole.SR_MANAGER_GLOBAL_PRODUCTION,
        signatory_name: 'Lindsey Schindler',
        signed_at: daysAgo(21).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st25',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(24).toISOString(),
        exited_at: daysAgo(23).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st26',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(23).toISOString(),
        exited_at: daysAgo(22).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st27',
        stage: 'PLANNING_MANAGER',
        entered_at: daysAgo(22).toISOString(),
        exited_at: daysAgo(21).toISOString(),
        sla_hours: 96,
        is_breached: false,
      },
      {
        id: 'st28',
        stage: 'LINDSEY',
        entered_at: daysAgo(21).toISOString(),
        exited_at: daysAgo(20).toISOString(),
        sla_hours: 72,
        is_breached: false,
      },
      {
        id: 'st29',
        stage: 'POLLY',
        entered_at: daysAgo(20).toISOString(),
        sla_hours: 72,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al25',
        invoice_id: 'inv17',
        action: 'APPROVED_BY_COORDINATOR',
        performed_by: 'Sarah Jane Cariquitan',
        note: 'Coordinator approval completed',
        created_at: daysAgo(23).toISOString(),
      },
      {
        id: 'al26',
        invoice_id: 'inv17',
        action: 'APPROVED_BY_MANAGER',
        performed_by: 'Maricar Tanaleon',
        note: 'Manager approval completed',
        created_at: daysAgo(22).toISOString(),
      },
      {
        id: 'al27',
        invoice_id: 'inv17',
        action: 'APPROVED_BY_PLANNING_MANAGER',
        performed_by: 'Edwin Garcia',
        note: 'Planning Manager approval completed',
        created_at: daysAgo(21).toISOString(),
      },
      {
        id: 'al28',
        invoice_id: 'inv17',
        action: 'APPROVED_BY_SR_MANAGER',
        performed_by: 'Lindsey Schindler',
        note: 'Sr Manager approval completed',
        created_at: daysAgo(20).toISOString(),
      },
    ],
  },
  // APPROVED (2 invoices)
  {
    id: 'inv18',
    invoice_number: 'INV-2026-0463',
    vendor_id: 'v7',
    vendor_name: 'R-PAC Vietnam Limited',
    total_amount: 1250.00,
    currency: 'USD',
    invoice_date: daysAgo(28).toISOString(),
    invoice_received_date: daysAgo(28).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Fjallraven',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-FJL-F26-011',
    status: InvoiceStatus.APPROVED,
    bank_name: 'Vietcombank',
    account_number: '3344556677',
    swift_code: 'BFTVVNVX',
    signatures: [
      {
        id: 'sig18',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(27).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig19',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Maricar Tanaleon',
        signed_at: daysAgo(26).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st30',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(27).toISOString(),
        exited_at: daysAgo(26).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st31',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(26).toISOString(),
        exited_at: daysAgo(25).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al29',
        invoice_id: 'inv18',
        action: 'APPROVED_BY_MANAGER',
        performed_by: 'Maricar Tanaleon',
        note: 'Final approval completed (Tier 1)',
        created_at: daysAgo(25).toISOString(),
      },
    ],
  },
  {
    id: 'inv19',
    invoice_number: 'INV-2026-0464',
    vendor_id: 'v4',
    vendor_name: 'Amass International Limited',
    total_amount: 3200.00,
    currency: 'USD',
    invoice_date: daysAgo(30).toISOString(),
    invoice_received_date: daysAgo(30).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Prana',
    brand_tier: 'OTHER',
    season: 'S26',
    order_type: 'BULK',
    po_number: 'PO-PRN-S26-003',
    status: InvoiceStatus.APPROVED,
    bank_name: 'Hang Seng Bank',
    account_number: '5566778899',
    swift_code: 'HASEHKHH',
    signatures: [
      {
        id: 'sig20',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Mariane Eusebio',
        signed_at: daysAgo(29).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig21',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Mary Ann Del Monte',
        signed_at: daysAgo(28).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig22',
        signatory_role: SignatoryRole.MLO_PLANNING_MANAGER,
        signatory_name: 'Glecie Yumena',
        signed_at: daysAgo(27).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig23',
        signatory_role: SignatoryRole.SR_MANAGER_GLOBAL_PRODUCTION,
        signatory_name: 'Lindsey Schindler',
        signed_at: daysAgo(26).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st32',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(29).toISOString(),
        exited_at: daysAgo(28).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st33',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(28).toISOString(),
        exited_at: daysAgo(27).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st34',
        stage: 'PLANNING_MANAGER',
        entered_at: daysAgo(27).toISOString(),
        exited_at: daysAgo(26).toISOString(),
        sla_hours: 96,
        is_breached: false,
      },
      {
        id: 'st35',
        stage: 'LINDSEY',
        entered_at: daysAgo(26).toISOString(),
        exited_at: daysAgo(25).toISOString(),
        sla_hours: 72,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al30',
        invoice_id: 'inv19',
        action: 'APPROVED_BY_SR_MANAGER',
        performed_by: 'Lindsey Schindler',
        note: 'Final approval completed (Tier 2)',
        created_at: daysAgo(25).toISOString(),
      },
    ],
  },
  // POSTED (3 invoices)
  {
    id: 'inv20',
    invoice_number: '100703828',
    vendor_id: 'v2',
    vendor_name: 'Avery Dennison Hong Kong B.V.',
    total_amount: 37.94,
    currency: 'USD',
    invoice_date: daysAgo(35).toISOString(),
    invoice_received_date: daysAgo(35).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'The North Face',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-TNF-F26-012',
    status: InvoiceStatus.POSTED_TO_QB,
    qb_invoice_id: 'QB-100703828',
    qb_posted_at: daysAgo(30).toISOString(),
    bank_name: 'HSBC Hong Kong',
    account_number: '0987654321',
    swift_code: 'HSBCHKHH',
    signatures: [
      {
        id: 'sig24',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(34).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig25',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Maricar Tanaleon',
        signed_at: daysAgo(33).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st36',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(34).toISOString(),
        exited_at: daysAgo(33).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st37',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(33).toISOString(),
        exited_at: daysAgo(32).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st38',
        stage: 'ACCOUNTING',
        entered_at: daysAgo(32).toISOString(),
        exited_at: daysAgo(31).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al31',
        invoice_id: 'inv20',
        action: 'POSTED_TO_QB',
        performed_by: 'Joy Yco',
        note: 'Posted to QuickBooks',
        created_at: daysAgo(30).toISOString(),
      },
    ],
  },
  {
    id: 'inv21',
    invoice_number: 'INV-2026-0465',
    vendor_id: 'v1',
    vendor_name: 'Avery Dennison Paxar (China) Ltd',
    total_amount: 2450.00,
    currency: 'USD',
    invoice_date: daysAgo(38).toISOString(),
    invoice_received_date: daysAgo(38).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Columbia Sportswear',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-COL-F26-013',
    status: InvoiceStatus.POSTED_TO_QB,
    qb_invoice_id: 'QB-INV-2026-0465',
    qb_posted_at: daysAgo(33).toISOString(),
    bank_name: 'Bank of China',
    account_number: '1234567890',
    swift_code: 'BKCHCNBJ',
    signatures: [
      {
        id: 'sig26',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Mariane Eusebio',
        signed_at: daysAgo(37).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig27',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Mary Ann Del Monte',
        signed_at: daysAgo(36).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig28',
        signatory_role: SignatoryRole.MLO_PLANNING_MANAGER,
        signatory_name: 'Edwin Garcia',
        signed_at: daysAgo(35).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig29',
        signatory_role: SignatoryRole.SR_MANAGER_GLOBAL_PRODUCTION,
        signatory_name: 'Lindsey Schindler',
        signed_at: daysAgo(34).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st39',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(37).toISOString(),
        exited_at: daysAgo(36).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st40',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(36).toISOString(),
        exited_at: daysAgo(35).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st41',
        stage: 'PLANNING_MANAGER',
        entered_at: daysAgo(35).toISOString(),
        exited_at: daysAgo(34).toISOString(),
        sla_hours: 96,
        is_breached: false,
      },
      {
        id: 'st42',
        stage: 'LINDSEY',
        entered_at: daysAgo(34).toISOString(),
        exited_at: daysAgo(33).toISOString(),
        sla_hours: 72,
        is_breached: false,
      },
      {
        id: 'st43',
        stage: 'ACCOUNTING',
        entered_at: daysAgo(33).toISOString(),
        exited_at: daysAgo(32).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al32',
        invoice_id: 'inv21',
        action: 'POSTED_TO_QB',
        performed_by: 'Joy Yco',
        note: 'Posted to QuickBooks',
        created_at: daysAgo(33).toISOString(),
      },
    ],
  },
  {
    id: 'inv22',
    invoice_number: 'INV-2026-0466',
    vendor_id: 'v7',
    vendor_name: 'R-PAC Vietnam Limited',
    total_amount: 1850.00,
    currency: 'USD',
    invoice_date: daysAgo(40).toISOString(),
    invoice_received_date: daysAgo(40).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Fjallraven',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-FJL-F26-014',
    status: InvoiceStatus.POSTED_TO_QB,
    qb_invoice_id: 'QB-INV-2026-0466',
    qb_posted_at: daysAgo(35).toISOString(),
    bank_name: 'Vietcombank',
    account_number: '3344556677',
    swift_code: 'BFTVVNVX',
    signatures: [
      {
        id: 'sig30',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(39).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig31',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Maricar Tanaleon',
        signed_at: daysAgo(38).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st44',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(39).toISOString(),
        exited_at: daysAgo(38).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st45',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(38).toISOString(),
        exited_at: daysAgo(37).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st46',
        stage: 'ACCOUNTING',
        entered_at: daysAgo(37).toISOString(),
        exited_at: daysAgo(36).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al33',
        invoice_id: 'inv22',
        action: 'POSTED_TO_QB',
        performed_by: 'Joy Yco',
        note: 'Posted to QuickBooks',
        created_at: daysAgo(35).toISOString(),
      },
    ],
  },
  // PAID (2 invoices)
  {
    id: 'inv23',
    invoice_number: '261000124',
    vendor_id: 'v7',
    vendor_name: 'R-PAC Vietnam Limited',
    total_amount: 3392.89,
    currency: 'USD',
    invoice_date: daysAgo(45).toISOString(),
    invoice_received_date: daysAgo(45).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Fjallraven',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-FJL-F26-015',
    status: InvoiceStatus.PAID,
    paid_at: daysAgo(10).toISOString(),
    payment_batch_id: 'pb1',
    bank_name: 'Vietcombank',
    account_number: '3344556677',
    swift_code: 'BFTVVNVX',
    signatures: [
      {
        id: 'sig32',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(44).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig33',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Maricar Tanaleon',
        signed_at: daysAgo(43).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st47',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(44).toISOString(),
        exited_at: daysAgo(43).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st48',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(43).toISOString(),
        exited_at: daysAgo(42).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st49',
        stage: 'ACCOUNTING',
        entered_at: daysAgo(42).toISOString(),
        exited_at: daysAgo(41).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al34',
        invoice_id: 'inv23',
        action: 'PAID',
        performed_by: 'system',
        note: 'Payment processed via batch pb1',
        created_at: daysAgo(10).toISOString(),
      },
    ],
  },
  {
    id: 'inv24',
    invoice_number: 'INV-2026-0467',
    vendor_id: 'v1',
    vendor_name: 'Avery Dennison Paxar (China) Ltd',
    total_amount: 4250.00,
    currency: 'USD',
    invoice_date: daysAgo(50).toISOString(),
    invoice_received_date: daysAgo(50).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.INVOICE,
    category: InvoiceCategory.TRIMS,
    brand: 'Columbia Sportswear',
    brand_tier: 'TOP_10',
    season: 'F26',
    order_type: 'BULK',
    po_number: 'PO-COL-F26-016',
    status: InvoiceStatus.PAID,
    paid_at: daysAgo(15).toISOString(),
    payment_batch_id: 'pb1',
    bank_name: 'Bank of China',
    account_number: '1234567890',
    swift_code: 'BKCHCNBJ',
    signatures: [
      {
        id: 'sig34',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Mariane Eusebio',
        signed_at: daysAgo(49).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig35',
        signatory_role: SignatoryRole.PURCHASING_MANAGER,
        signatory_name: 'Mary Ann Del Monte',
        signed_at: daysAgo(48).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig36',
        signatory_role: SignatoryRole.MLO_PLANNING_MANAGER,
        signatory_name: 'Edwin Garcia',
        signed_at: daysAgo(47).toISOString(),
        signature_type: 'DIGITAL',
      },
      {
        id: 'sig37',
        signatory_role: SignatoryRole.SR_MANAGER_GLOBAL_PRODUCTION,
        signatory_name: 'Lindsey Schindler',
        signed_at: daysAgo(46).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st50',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(49).toISOString(),
        exited_at: daysAgo(48).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st51',
        stage: 'PURCHASING_MANAGER',
        entered_at: daysAgo(48).toISOString(),
        exited_at: daysAgo(47).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st52',
        stage: 'PLANNING_MANAGER',
        entered_at: daysAgo(47).toISOString(),
        exited_at: daysAgo(46).toISOString(),
        sla_hours: 96,
        is_breached: false,
      },
      {
        id: 'st53',
        stage: 'LINDSEY',
        entered_at: daysAgo(46).toISOString(),
        exited_at: daysAgo(45).toISOString(),
        sla_hours: 72,
        is_breached: false,
      },
      {
        id: 'st54',
        stage: 'ACCOUNTING',
        entered_at: daysAgo(45).toISOString(),
        exited_at: daysAgo(44).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al35',
        invoice_id: 'inv24',
        action: 'PAID',
        performed_by: 'system',
        note: 'Payment processed via batch pb1',
        created_at: daysAgo(15).toISOString(),
      },
    ],
  },
  // PI_PENDING_CI (1 invoice)
  {
    id: 'inv25',
    invoice_number: '26U6BNFMDS-001Z',
    vendor_id: 'v9',
    vendor_name: 'Zhejiang Weixing',
    total_amount: 33.30,
    currency: 'USD',
    invoice_date: daysAgo(20).toISOString(),
    invoice_received_date: daysAgo(20).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.PROFORMA,
    category: InvoiceCategory.TRIMS,
    status: InvoiceStatus.PAID,
    paid_at: daysAgo(14).toISOString(),
    bank_name: 'Industrial and Commercial Bank of China',
    account_number: '2233445566',
    swift_code: 'ICBKCNBJ',
    signatures: [
      {
        id: 'sig38',
        signatory_role: SignatoryRole.COORDINATOR,
        signatory_name: 'Sarah Jane Cariquitan',
        signed_at: daysAgo(19).toISOString(),
        signature_type: 'DIGITAL',
      },
    ],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st55',
        stage: 'PURCHASING_COORDINATOR',
        entered_at: daysAgo(19).toISOString(),
        exited_at: daysAgo(18).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
      {
        id: 'st56',
        stage: 'ACCOUNTING',
        entered_at: daysAgo(18).toISOString(),
        exited_at: daysAgo(17).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al36',
        invoice_id: 'inv25',
        action: 'PAID',
        performed_by: 'system',
        note: 'Proforma Invoice paid',
        created_at: daysAgo(14).toISOString(),
      },
    ],
    follow_up_tasks: [
      {
        id: 'ft1',
        invoice_id: 'inv25',
        task_type: 'REQUEST_CI',
        assigned_to: 'Mariane Eusebio',
        due_date: daysAgo(0).toISOString(),
        status: 'PENDING',
        reminder_count: 1,
        last_reminded_at: daysAgo(7).toISOString(),
        notes: 'Request Commercial/Sales Invoice from vendor Zhejiang Weixing for PI 26U6BNFMDS-001Z, paid on 2026-06-05',
        created_at: daysAgo(14).toISOString(),
      },
    ],
  },
  // STATEMENT (1 invoice)
  {
    id: 'inv26',
    invoice_number: '8526250996IN202604',
    vendor_id: 'v12',
    vendor_name: 'S.F. Express (Hong Kong) Limited',
    total_amount: 28.21,
    currency: 'USD',
    invoice_date: daysAgo(5).toISOString(),
    invoice_received_date: daysAgo(5).toISOString(),
    payment_terms: 'NET 30',
    invoice_type: InvoiceType.STATEMENT,
    category: InvoiceCategory.SHIPPING_FREIGHT,
    status: InvoiceStatus.PENDING_ACCOUNTING,
    bank_name: 'Bank of East Asia',
    account_number: '0012345678',
    swift_code: 'BEASHKHH',
    signatures: [],
    exceptions: [],
    stage_timestamps: [
      {
        id: 'st57',
        stage: 'ACCOUNTING',
        entered_at: daysAgo(4).toISOString(),
        sla_hours: 168,
        is_breached: false,
      },
    ],
    audit_logs: [
      {
        id: 'al37',
        invoice_id: 'inv26',
        action: 'INVOICE_RECEIVED',
        performed_by: 'system',
        note: 'Statement invoice received',
        created_at: daysAgo(5).toISOString(),
      },
    ],
  },
];

// Mock Payment Batches
export const MOCK_PAYMENT_BATCHES: MockPaymentBatch[] = [
  {
    id: 'pb1',
    batch_name: 'Week 24 - June 2026',
    status: 'PROCESSED',
    total_amount: 7642.89,
    currency: 'USD',
    due_date: daysAgo(15).toISOString(),
    invoice_count: 2,
    invoices: ['inv23', 'inv24'],
    created_at: daysAgo(20).toISOString(),
    processed_at: daysAgo(15).toISOString(),
    confirmation_pdf: 'batch_pb1_confirmation.pdf',
  },
  {
    id: 'pb2',
    batch_name: 'Week 25 - June 2026',
    status: 'DRAFT',
    total_amount: 8500.00,
    currency: 'USD',
    due_date: daysAgo(3).toISOString(),
    invoice_count: 5,
    invoices: ['inv18', 'inv19', 'inv20', 'inv21', 'inv22'],
    created_at: daysAgo(7).toISOString(),
  },
  {
    id: 'pb3',
    batch_name: 'Week 26 - June 2026',
    status: 'PENDING_CFO',
    total_amount: 12300.00,
    currency: 'USD',
    due_date: daysAgo(10).toISOString(),
    invoice_count: 3,
    invoices: ['inv13', 'inv15', 'inv16'],
    created_at: daysAgo(14).toISOString(),
    submitted_at: daysAgo(12).toISOString(),
  },
];

// Mock Reports Data
export const MOCK_REPORTS = {
  weeklyPaymentPrioritization: [
    { invoice_number: 'INV-2026-0463', vendor: 'R-PAC Vietnam', amount: 1250.00, due_date: daysAgo(2).toISOString() },
    { invoice_number: 'INV-2026-0464', vendor: 'Amass International', amount: 3200.00, due_date: daysAgo(3).toISOString() },
    { invoice_number: 'INV-2026-0465', vendor: 'Avery Dennison HK', amount: 2450.00, due_date: daysAgo(4).toISOString() },
    { invoice_number: 'INV-2026-0466', vendor: 'R-PAC Vietnam', amount: 1850.00, due_date: daysAgo(5).toISOString() },
    { invoice_number: '100703828', vendor: 'Avery Dennison HK', amount: 37.94, due_date: daysAgo(6).toISOString() },
  ],
  payablesAging: {
    current: 4200.00,
    day30: 1850.00,
    day60: 620.00,
    day90: 0.00,
  },
  supplierBalance: [
    { vendor: 'Avery Dennison HK', received: 8, recorded: 7, gap: 1 },
    { vendor: 'R-PAC Vietnam', received: 5, recorded: 5, gap: 0 },
    { vendor: 'Amass International', received: 3, recorded: 3, gap: 0 },
  ],
  slaCompliance: {
    overall: 87,
    byStage: {
      PURCHASING_COORDINATOR: 92,
      PURCHASING_MANAGER: 88,
      PLANNING_MANAGER: 85,
      LINDSEY: 90,
      ACCOUNTING: 82,
    },
  },
};
